name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    name: Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17, 21, 22, 24 ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: maven
    - name: Build with Maven
      shell: bash
      run: |
        mvn -B install
        cat japicmp/target/japicmp/github-job-summary.md  >$GITHUB_STEP_SUMMARY
