name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    name: Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17, 18, 19, 21, 22 ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: maven
    - name: Build with Maven
      run: mvn -B package
    - name: japicmp report in Job Summary
      run:  cat ./japicmp-testbase/japicmp-test-maven-plugin/target/japicmp/github-job-summary.md >> GITHUB_STEP_SUMMARY
